name: BetterWarps
version: 1.0.0
main: HansenKhi\BetterWarps\BetterWarps
api: 4.0.0
author: HansenKhi

commands:
  warp:
    usage: /warp <create/remove>
    description: Create/Remove a Warp
    permission: betterwarps.cmd
  to:
    usage: /to <Warp Name>
    description: Teleport to warp
    permission: betterwarps.warp

permissions:
  betterwarps.cmd:
    description: Permission to manage warps
    default: op
  betterwarps.warp:
    description: Permission to warp
    default: true
